# Generated by Django 4.1.5 on 2023-03-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_category_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
