# Generated by Django 4.1.5 on 2023-03-01 18:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=1, verbose_name='Ürün ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ürün Başlığı')),
                ('descripiton', ckeditor.fields.RichTextField(blank=True, verbose_name='Ürün Açıklaması')),
                ('images', models.JSONField(blank=True, null=True, verbose_name='Resimler')),
                ('special_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Özel Alan 3')),
                ('special_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Özel Alan 4')),
                ('special_5', models.CharField(blank=True, max_length=200, null=True, verbose_name='Özel Alan 5')),
                ('variations', models.JSONField(blank=True, null=True, verbose_name='Resimler')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Kategori')),
            ],
        ),
    ]
