# Generated by Django 4.1.5 on 2023-03-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_categories_alter_product_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripiton',
            new_name='description',
        ),
    ]
