# Generated by Django 4.1.5 on 2023-03-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_special_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='special_2',
        ),
    ]
