# Generated by Django 4.1.5 on 2023-02-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Banka')),
            ],
            options={
                'verbose_name_plural': 'banks',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Taksit Durumu')),
            ],
            options={
                'verbose_name_plural': 'installment statuses',
            },
        ),
        migrations.CreateModel(
            name='LoanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kredi Durumu')),
            ],
            options={
                'verbose_name_plural': 'loan statuses',
            },
        ),
    ]
