# Generated by Django 4.1.5 on 2023-02-22 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kredi İsmi')),
                ('amount', models.FloatField(default=0.0, verbose_name='Kredi Tutarı')),
                ('cost', models.FloatField(default=0.0, verbose_name='Masraf')),
                ('transmitted_amount', models.FloatField(blank=True, null=True, verbose_name='Hesaba Aktarılan Tutar')),
                ('interest', models.FloatField(default=0.0, verbose_name='Faiz')),
                ('total_debt', models.FloatField(blank=True, null=True, verbose_name='Toplam Borç')),
                ('installment_count', models.IntegerField(default=1, verbose_name='Taksit Sayısı')),
                ('installments', models.JSONField(verbose_name='Taksitler')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('bank', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='loan.bank', verbose_name='Banka')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='loan.loanstatus', verbose_name='Kredi Durumu')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
