# Generated by Django 4.1.5 on 2023-02-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Giriş Seçeneği')),
            ],
            options={
                'verbose_name_plural': 'loan options',
            },
        ),
    ]
