# Generated by Django 4.1.5 on 2023-02-23 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loanoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='loan.loanoption', verbose_name='Hesaplama/Giriş'),
        ),
        migrations.AlterField(
            model_name='loanoption',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Hesaplama'),
        ),
    ]
