# Generated by Django 4.1.5 on 2023-02-24 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_loan_option_alter_loanoption_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='installments',
            field=models.JSONField(blank=True, null=True, verbose_name='Taksitler'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Kredi Başlangıç Tarihi'),
        ),
    ]
