# Generated by Django 4.1.5 on 2023-02-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_loan_installments_alter_loan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='installment_deferral',
            field=models.IntegerField(default=0, verbose_name='Taksit Erteleme'),
        ),
    ]
