# Generated by Django 4.1.5 on 2023-02-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_loan_installment_deferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='next_installment',
            field=models.DateField(blank=True, null=True, verbose_name='Taksitler'),
        ),
    ]
