# Generated by Django 4.1.5 on 2023-02-27 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_loan_next_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='installment_status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='loan.installmentstatus', verbose_name='Taksit Durumu'),
        ),
    ]
