# Generated by Django 4.1.5 on 2023-03-07 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0017_alter_loan_installment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCHLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kredi İsmi')),
                ('amount', models.FloatField(default=0.0, verbose_name='Anapara')),
                ('remaining_amount', models.FloatField(default=0.0, verbose_name='Kalan Anapara')),
                ('cost', models.FloatField(default=0.0, verbose_name='Masraf')),
                ('transmitted_amount', models.FloatField(blank=True, null=True, verbose_name='Hesaba Aktarılan Tutar')),
                ('interest', models.FloatField(default=0.0, verbose_name='Faiz')),
                ('interest_amount', models.FloatField(default=0.0, verbose_name='Faiz Tutarı')),
                ('total_debt', models.FloatField(blank=True, null=True, verbose_name='Toplam Borç')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Kredi Başlangıç Tarihi')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Kredi Bitiş Tarihi')),
                ('interest_payment', models.JSONField(blank=True, null=True, verbose_name='Faiz Ödemeleri')),
                ('amount_payment', models.JSONField(blank=True, null=True, verbose_name='Anapara Ödemeleri')),
                ('interest_updates', models.JSONField(blank=True, null=True, verbose_name='Faiz Güncellemeleri')),
                ('bank', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='loan.bank', verbose_name='Banka')),
                ('option', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='loan.loanoption', verbose_name='Hesaplama/Giriş')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='loan.loanstatus', verbose_name='Kredi Durumu')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
