# Generated by Django 4.1.5 on 2023-01-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
