# Generated by Django 4.1.5 on 2023-02-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['title']},
        ),
    ]
