# Generated by Django 4.1.5 on 2023-01-31 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 10, 6, 32, 32136)),
        ),
    ]
