# Generated by Django 4.1.5 on 2023-01-31 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0011_excel_alter_expense_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 31, 17, 33, 2, 285598, tzinfo=datetime.timezone.utc), verbose_name='Tarih'),
        ),
    ]
