# Generated by Django 4.1.5 on 2023-01-31 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0012_alter_expense_created_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 31, 18, 39, 15, 892335, tzinfo=datetime.timezone.utc), verbose_name='Tarih'),
        ),
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
    ]
