# Generated by Django 4.1.5 on 2023-02-01 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0015_alter_expense_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expense.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tarih'),
        ),
    ]
