# Generated by Django 4.1.5 on 2023-02-07 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kategori')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Birim')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kaynak')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'sources',
                'unique_together': {('slug',)},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Malzeme İsmi')),
                ('quantity', models.FloatField(default=1, verbose_name='Miktar')),
                ('price', models.FloatField(default=0.0, verbose_name='Birim Fiyat')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='material.category', verbose_name='Kategori')),
                ('source', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='material.source', verbose_name='Kaynak')),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='material.unit', verbose_name='Birim')),
            ],
        ),
    ]
