# Generated by Django 4.1.5 on 2023-01-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Kaynak')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'sources',
                'unique_together': {('slug',)},
            },
        ),
    ]
