# Generated by Django 4.1.5 on 2023-01-26 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_source_id_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('Diğer', 'diger'), ('Menteşe', 'mentese'), ('Ray', 'ray')], default='diger', max_length=30),
        ),
        migrations.AlterField(
            model_name='material',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.source', verbose_name='Kaynak'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Malzeme'),
        ),
    ]
