# Generated by Django 4.1.5 on 2023-01-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_material_type_alter_material_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Miktar'),
        ),
        migrations.AddField(
            model_name='material',
            name='quantity_type',
            field=models.CharField(choices=[('Adet', 'adet'), ('Kg', 'kg'), ('Gr', 'gr'), ('L', 'l')], default='adet', max_length=30),
        ),
    ]
