# Generated by Django 4.1.5 on 2023-01-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_material_quantity_material_quantity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Miktar'),
        ),
    ]
