# Generated by Django 4.1.5 on 2023-01-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_alter_material_quantity_type_alter_material_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Birim Fiyat'),
        ),
    ]
