# Generated by Django 4.1.5 on 2023-01-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_material_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='Miktar'),
        ),
    ]
