# Generated by Django 4.1.5 on 2023-01-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_alter_material_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='quantity_type',
            field=models.CharField(choices=[('adet', 'Adet'), ('kilogram', 'Kg'), ('gram', 'Gr'), ('litre', 'Litre'), ('metre', 'Metre'), ('metrekare', 'm2'), ('desimetrekup', 'dm3')], default='adet', max_length=30, verbose_name='Birim'),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('diger', 'Diğer'), ('mentese', 'Menteşe'), ('ray', 'Ray')], default='diger', max_length=30, verbose_name='Malzeme Tipi'),
        ),
    ]
