# Generated by Django 4.1.5 on 2023-01-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_alter_material_quantity_type_alter_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('diger', 'Diğer'), ('mentese', 'Menteşe'), ('ray', 'Ray'), ('mese_kereste', 'Meşe Kereste'), ('kayin_kereste', 'Kayın Kereste'), ('kaplamali_mdf_18', 'Kaplamalı MDF 18'), ('kaplamali_mdf_25', 'Kaplamalı MDF 25'), ('ham_mdf_18', 'Ham MDF 18'), ('cekmece_mdf', 'Çekmece MDF'), ('aralik', 'Aralık'), ('tutkal', 'Tutkal'), ('kenar_bandi', 'Kenar Bandı'), ('maxifix', 'Maxifix'), ('l_baglanti', 'L Bağlantı'), ('minifix', 'Minifix'), ('aski_takimi', 'Askı Takımı'), ('ayna', 'Ayna'), ('raf_pimi', 'Raf Pimi'), ('cnc', 'CNC'), ('boya', 'Boya'), ('kulp', 'Kulp'), ('lata', 'Lata'), ('doseme', 'Döşeme'), ('hazeran', 'Hazeran'), ('torna', 'Torna'), ('paketleme', 'Paketleme'), ('nakliye', 'Nakliye'), ('google', 'Google')], default='diger', max_length=30, verbose_name='Malzeme Tipi'),
        ),
    ]
