# Generated by Django 4.1.5 on 2023-01-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0011_category_material_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
    ]
