# Generated by Django 4.1.5 on 2023-01-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0013_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
