# Generated by Django 4.1.5 on 2023-01-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0014_delete_category'),
    ]

    operations = [
    ]
