# Generated by Django 4.1.5 on 2023-01-30 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0016_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='material.category', verbose_name='Kategori'),
        ),
    ]
