# Generated by Django 4.1.5 on 2023-01-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0017_material_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='type',
        ),
    ]
