# Generated by Django 4.1.5 on 2023-01-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0018_remove_material_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Birim')),
            ],
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-title']},
        ),
    ]
