# Generated by Django 4.1.5 on 2023-01-30 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0019_unit_alter_material_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='quantity_type',
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='material.unit', verbose_name='Birim'),
        ),
    ]
