# Generated by Django 4.1.5 on 2023-01-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0020_remove_material_quantity_type_material_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={},
        ),
    ]
