# Generated by Django 4.1.5 on 2023-02-01 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0021_alter_material_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='source',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='material.source', verbose_name='Kaynak'),
        ),
    ]
