# Generated by Django 4.1.5 on 2023-02-02 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Usta', 'usta'), ('Yönetici', 'yonetici'), ('Müşteri', 'musteri'), ('Cari', 'cari')], default='usta', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to=user.models.user_directory_path, verbose_name='Profil Resmi')),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tel No')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
