# Generated by Django 4.1.5 on 2023-02-07 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCategory',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='user.category', verbose_name='Kategori'),
        ),
    ]
