# Generated by Django 4.1.5 on 2023-01-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_type',
            field=models.CharField(choices=[('Usta', 'usta'), ('Yönetici', 'yonetici'), ('Müşteri', 'musteri'), ('Cari', 'cari')], default='usta', max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tel No'),
        ),
    ]
