# Generated by Django 4.1.5 on 2023-02-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230207_1152'),
    ]

    operations = [
        migrations.RenameField("Employee", "category", "user_category")
    ]
