# Generated by Django 4.1.5 on 2023-02-07 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230207_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffCtegory',
        ),
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name_plural': 'user categories'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='user.usercategory', verbose_name='Kullanıcı Kategorisi'),
        ),
    ]
