# Generated by Django 4.1.5 on 2023-02-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_staffctegory_alter_usercategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Personel Kategorisi')),
            ],
            options={
                'verbose_name_plural': 'staff categories',
            },
        ),
    ]
