# Generated by Django 4.1.5 on 2023-02-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_staffcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='staff_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='user.staffcategory', verbose_name='Personel Kategorisi'),
        ),
    ]
