# Generated by Django 4.1.5 on 2023-02-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_employee_staff_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user_type',
        ),
    ]
