# Generated by Django 4.1.5 on 2023-02-07 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_employee_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='staff_category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='user.staffcategory', verbose_name='Personel Kategorisi'),
        ),
    ]
