# Generated by Django 4.1.5 on 2023-02-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_employee_staff_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='user.usercategory', verbose_name='Kullanıcı Kategorisi'),
        ),
    ]
