# Generated by Django 4.1.5 on 2023-02-13 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sipariş Durumu')),
            ],
            options={
                'verbose_name_plural': 'statuses',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=1, max_length=200, verbose_name='Müşteri Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sipariş Tarihi'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=1, verbose_name='Sipariş ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.JSONField(default=1, verbose_name='Ürünler'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
    ]
