# Generated by Django 4.1.5 on 2023-02-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0.0, verbose_name='Sipariş Tutarı'),
        ),
    ]
